---
title: "R Notebook"
output: html_notebook
---

### **Homework 1 Solutions**

### **Problem 1**
```{r}
quicksort = function(x) {
  if (length(x) <= 1) {
    return(x)
  }
  else {
    pivot = x[1]
    left = x[x<pivot]
    middle = x[x==pivot]
    right = x[x>pivot]
    return(c(quicksort(left), middle, quicksort(right)))
  }
}

set.seed(42)
vec = sample(1:50, 10)
vec

sorted_vec = quicksort(vec)
sorted_vec
```
<br>

### **Problem 2**
(See Canvas under the Solutions Module)
<br>

### **Problem 3**
```{r}
library(tidyverse)
library(rsample)

data("ToothGrowth")

tooth_data = ToothGrowth

set.seed(42)

split = initial_split(tooth_data, prop=0.8)

train_set = training(split)
test_set = testing(split)

nrow(tooth_data) # 60 rows
nrow(train_set) # 48 rows
nrow(test_set) # 12 rows

head(train_set)
head(test_set)
```

<br>

### **Problem 4**
```{r}
data(iris)
iris_data = iris

# (a)

head(iris_data)

# (b)

dim(iris_data)
colnames(iris_data)

# (c) Should be 4, let's check this.

iris_data$Sepal.Width[15]

# (d) 

iris_data$Sepal.Length[5] = 10.6
iris_data$Sepal.Width[c(1, 3)] = 25.1
head(iris_data)
```

<br>
